### ISSUE TITLE
Repo missing `package.json`

### ISSUE THREAD

**Issue by brettz9** [AWinterman/node-mdls#4]
Your repo is missing a `package.json` (despite the package being available on npm). When cloning your repo and trying to target my fork via npm, I got an error about this. Thanks!

**Comment by brettz9** [comment]
If you're not maintaining this, I guess I may publish my own repo for this then... Are you still maintaining this project?

**Comment by AWinterman** [comment]
add one and i’ll merge it. i’m not really using it. i can also add you as a contributor.

**Comment by brettz9** [comment]
Adding me as a contributor would be cool too...
